version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: awslegal-db
    restart: always
    environment:
      POSTGRES_DB: awslegal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aws2025
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
